# Generated by Django 4.0 on 2022-01-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs50wfinal', '0002_alter_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
